USE [master]
GO

/****** Object:  Database [staffData]    Script Date: 3/19/2024 2:29:55 AM ******/
CREATE DATABASE [staffData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'staffData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\staffData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'staffData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\staffData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [staffData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [staffData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [staffData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [staffData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [staffData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [staffData] SET ARITHABORT OFF 
GO

ALTER DATABASE [staffData] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [staffData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [staffData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [staffData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [staffData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [staffData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [staffData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [staffData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [staffData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [staffData] SET  ENABLE_BROKER 
GO

ALTER DATABASE [staffData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [staffData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [staffData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [staffData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [staffData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [staffData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [staffData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [staffData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [staffData] SET  MULTI_USER 
GO

ALTER DATABASE [staffData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [staffData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [staffData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [staffData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [staffData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [staffData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [staffData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [staffData] SET  READ_WRITE 
GO


